/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CR.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "Clock.h"
#include "MUX1_aliases.h"
#include "MUX1.h"
#include "AD5941_aliases.h"
#include "AD5941.h"
#include "MUX6_aliases.h"
#include "MUX6.h"
#include "MUX5_aliases.h"
#include "MUX5.h"
#include "MUX4_aliases.h"
#include "MUX4.h"
#include "MUX3_aliases.h"
#include "MUX3.h"
#include "MUX2_aliases.h"
#include "MUX2.h"
#include "ADC_DelSig.h"
#include "isr_1.h"
#include "AD5941_Interrupt_aliases.h"
#include "AD5941_Interrupt.h"
#include "AD5941_Reset_aliases.h"
#include "AD5941_Reset.h"
#include "Reset_CR.h"
#include "Sensor1_p_aliases.h"
#include "Sensor1_p.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "Sensor1_m_aliases.h"
#include "Sensor1_m.h"
#include "DMA_RX_dma.h"
#include "DMA_TX_dma.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

